---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Setting up test environment.
      debug:
        msg:
          - '==============================================================='
          - 'Pre tasks'
          - '==============================================================='

    - name: Ensure Python requirements installed.
      apt:
        name:
          - python
          - python-pip
          - python-setuptools
          - python3-pip
          - python3-setuptools
        state: present
      changed_when: false

    - name: Ensure Pip requirements installed.
      pip:
        name:
          - flake8
          - requests
      become: false
      changed_when: false

  roles:
    - role: jsnode
      packages_js: []
      configuration: https://is.gd/BHgGUt
      expand: true

  post_tasks:
    - name: Run verification tests.
      debug:
        msg:
          - '================================================================'
          - 'Post tasks'
          - '================================================================'

    - name: Verify node-red package installed.
      command: yarn global list
      register: yarn_list_result
      become: true
      changed_when: false
      failed_when: "'red' not in yarn_list_result.stdout"